### ISSUE TITLE
http://localhost:3000/apidoc访问报错（见截图)

### ISSUE THREAD

**Issue by seaify** [windy/lina#15]
rails new lina
gem install lina
rails g lina:install
rails s
然后本地http://localhost:3000/apidoc访问就报错了, 在mac和ubuntu环境都是一样的错误，couldn't find file 'angular-route' with type 'application/javascript'

**Comment by seaify** [comment]
见截图链接:
https://www.dropbox.com/s/bfwujyl9i6s6jsv/Screenshot%202015-05-18%2017.57.12%282%29.png?dl=0

**Comment by seaify** [comment]
见截图链接:
https://www.dropbox.com/s/bfwujyl9i6s6jsv/Screenshot%202015-05-18%2017.57.12%282%29.png?dl=0

**Comment by windy** [comment]
@seaify 白天一直在外面, 刚有空查.

我这里完全按你的步骤都是正常的. 看样子不是 lina 的问题.

看这个错误,  应该是指向 rails-assets 的错误或者 bug, 不知道你的 Rails 依赖的 rails-assets 版本是多少? 如果可以, 可以把这个项目分享给我看一下. 或者先升级一下 rails-assets 看看问题还存在不.

**Comment by seaify** [comment]
chuck@proxy:~/tmp/lina % rails -v
Rails 4.2.1
chuck@proxy:~/tmp/lina % gem_search rails-assets
rails-assets (0.5.2)

另外rails-assets，在你提到之前，我并没有安装，如果你的项目需要用到它，得放在Gemfile里吧。

我直接给你机器的登陆账号和密码，方便些。微信给你。

**Comment by windy** [comment]
@seaify 

由于你的系统以前已经安装过 angularjs-rails 很旧的版本, 导致 lina 关联到了 angularjs-rails 1.0.x 的版本, 这个太旧了.( 大概是 2 年前的 angularjs 版本 )

执行 `bundle update angularjs-rails` 重新关联到 angularjs-rails 1.3.15 即解决了这个问题.

我在 lina 的 gemspec 为 angularjs 添加一个最低版本要求即可.
