### ISSUE TITLE
生成的APIDOC中出现未预期的api描述

### ISSUE THREAD

**Issue by comme** [windy/lina#2]
route:
```
  resources :posts
```

控制器中仅定义了
```
define_action :index
```
访问/apidoc,发现出现两个api描述，一个为 GET /posts(期望出现的),一个问题POST /posts(未预期的)

**Comment by windy** [comment]
根据路由协议, 你要这样定义: 

```ruby
resources :posts, only: [:index]
```

不然你使用 `rake routes` 也可以查到多条路由. Lina 正是根据路由表来生成的 APIDOC.

**Comment by comme** [comment]
哦，是匹配 路由表 和 action 并没有考虑到 HTTP method 来生成的api是吧？

**Comment by windy** [comment]
嗯, 不会去查找对应的 controller 与 index 是否存在. 


ps: rails 也会生成同样的路由, 只是调用时才出错.

**Comment by windy** [comment]
我看了一下, 在 lina 中添加这个检测是可行的. 不过建议养成写 only 或者 except 的好习惯.

**Comment by comme** [comment]
ok,了解

**Comment by windy** [comment]
@comme 现在生成 APIDOC 的时候会考虑实际的 action 了.
