### ISSUE TITLE
Lina::ReturnCheckError at /api/v1/sports/index The property '#/' of type Array did not match the following type: object

### ISSUE THREAD

**Issue by 85636682** [windy/lina#8]
返回检查的时候，按照例子写，出现这个错误
```
Lina::ReturnCheckError at /api/v1/sports/index
The property '#/' of type Array did not match the following type: object
```
代码：
```
return: {
      type: 'object',
      required: [ 'id', 'name', 'presentation' ],
      properties: {
        id: {
          type: 'integer',
        },
        name: {
          type: 'string',
        },
        presentation: {
          type: 'string'
        }
      }
    }
```

**Comment by windy** [comment]
这个提示是说, API 返回的值与约束不一致.

看提示是, 你返回了 Array 数据,  但声明的是对象( hash ).

**Comment by 85636682** [comment]
@windy 好的，顺便问问，比如我要做验证，想定义一个current_user和authenticate!的方法，我放在application_controller.rb，但是在API的controller里面，好像不能调用的？

**Comment by windy** [comment]
好的，我回头看一下。

**Comment by windy** [comment]
@85636682 我研究了一下, 问题出在,  Lina::ApplicationController 继承至 ActionController::Base, 所以你的控制台由于继承了 Lina::ApplicationController, 而不是 ::ApplicationController, 所以没法使用 application_controller.rb 的方法.

我觉得你的理解更符合 ** 不要惊讶 ** 的原则, 我已经发布了 0.0.3, 默认支持 application_controller.rb 的方法调用.

**Comment by 85636682** [comment]
@windy 好的！谢谢！
